import { DifficultyPreset, SandboxVars } from './sandbox-vars-types';

export const DIFFICULTY_PRESETS: Record<string, DifficultyPreset> = {
  apocalypse: {
    id: 'apocalypse',
    label: 'Apocalypse',
    description: 'Stealth focus. Short lifespan. Combat best avoided. The default hardcore experience with realistic combat.',
    config: {
      VERSION: 4,
      Zombies: 4,
      Distribution: 1,
      DayLength: 3,
      StartYear: 1,
      StartMonth: 7,
      StartDay: 9,
      StartTime: 2,
      WaterShut: 2,
      ElecShut: 2,
      WaterShutModifier: 500,
      ElecShutModifier: 480,
      FoodLoot: 4,
      WeaponLoot: 2,
      OtherLoot: 3,
      Temperature: 3,
      Rain: 3,
      ErosionSpeed: 5,
      XpMultiplier: 1.0,
      Farming: 3,
      StatsDecrease: 4,
      NatureAbundance: 3,
      Alarm: 6,
      LockedHouses: 6,
      StarterKit: false,
      Nutrition: true,
      FoodRotSpeed: 5,
      FridgeFactor: 5,
      LootRespawn: 2,
      TimeSinceApo: 1,
      PlantResilience: 3,
      PlantAbundance: 3,
      EndRegen: 3,
      ZombieLore: {
        Speed: 2,
        Strength: 2,
        Toughness: 2,
        Transmission: 1,
        Mortality: 6,
        Reanimate: 1,
        Cognition: 3,
        Memory: 2,
        Decomp: 1,
        Sight: 2,
        Hearing: 2,
        Smell: 2,
        ThumpNoChasing: true,
        ThumpOnConstruction: true,
        ActiveOnly: 1,
        TriggerHouseAlarm: false,
        ZombiesDragDown: true,
        ZombiesFenceLunge: true,
      },
      ZombieConfig: {
        PopulationMultiplier: 1.0,
        PopulationStartMultiplier: 1.0,
        PopulationPeakMultiplier: 1.5,
        PopulationPeakDay: 28,
        RespawnHours: 72.0,
        RespawnUnseenHours: 16.0,
        RespawnMultiplier: 0.1,
        RedistributeHours: 12.0,
        FollowSoundDistance: 100,
        RallyGroupSize: 20,
        RallyTravelDistance: 20,
        RallyGroupSeparation: 15,
        RallyGroupRadius: 3,
      },
    },
  },
  survivor: {
    id: 'survivor',
    label: 'Survivor',
    description: 'Powerful combat. Longer lifespan. A challenging playstyle based on PZ\'s previous Survival mode.',
    config: {
      VERSION: 4,
      Zombies: 3,
      Distribution: 1,
      DayLength: 3,
      StartYear: 1,
      StartMonth: 7,
      StartDay: 9,
      StartTime: 2,
      WaterShut: 2,
      ElecShut: 2,
      WaterShutModifier: 500,
      ElecShutModifier: 480,
      FoodLoot: 4,
      WeaponLoot: 2,
      OtherLoot: 3,
      Temperature: 3,
      Rain: 3,
      ErosionSpeed: 5,
      XpMultiplier: 1.0,
      Farming: 3,
      StatsDecrease: 4,
      NatureAbundance: 3,
      Alarm: 6,
      LockedHouses: 6,
      StarterKit: false,
      Nutrition: true,
      FoodRotSpeed: 5,
      FridgeFactor: 5,
      LootRespawn: 2,
      TimeSinceApo: 1,
      PlantResilience: 3,
      PlantAbundance: 3,
      EndRegen: 3,
      ZombieLore: {
        Speed: 2,
        Strength: 2,
        Toughness: 3,
        Transmission: 1,
        Mortality: 6,
        Reanimate: 1,
        Cognition: 3,
        Memory: 2,
        Decomp: 1,
        Sight: 2,
        Hearing: 2,
        Smell: 2,
        ThumpNoChasing: true,
        ThumpOnConstruction: true,
        ActiveOnly: 1,
        TriggerHouseAlarm: false,
        ZombiesDragDown: false,
        ZombiesFenceLunge: true,
      },
      ZombieConfig: {
        PopulationMultiplier: 1.0,
        PopulationStartMultiplier: 1.0,
        PopulationPeakMultiplier: 1.5,
        PopulationPeakDay: 28,
        RespawnHours: 72.0,
        RespawnUnseenHours: 16.0,
        RespawnMultiplier: 0.1,
        RedistributeHours: 12.0,
        FollowSoundDistance: 100,
        RallyGroupSize: 20,
        RallyTravelDistance: 20,
        RallyGroupSeparation: 15,
        RallyGroupRadius: 3,
      },
    },
  },
  builder: {
    id: 'builder',
    label: 'Builder',
    description: 'Construction, Exploration and Farming focus. A more relaxed experience with 80% fewer zombies.',
    config: {
      VERSION: 4,
      Zombies: 5,
      Distribution: 1,
      DayLength: 3,
      StartYear: 1,
      StartMonth: 7,
      StartDay: 9,
      StartTime: 2,
      WaterShut: 6,
      ElecShut: 6,
      WaterShutModifier: 500,
      ElecShutModifier: 480,
      FoodLoot: 5,
      WeaponLoot: 1,
      OtherLoot: 2,
      Temperature: 3,
      Rain: 3,
      ErosionSpeed: 5,
      XpMultiplier: 1.0,
      Farming: 3,
      StatsDecrease: 2,
      NatureAbundance: 3,
      Alarm: 6,
      LockedHouses: 6,
      StarterKit: false,
      Nutrition: true,
      FoodRotSpeed: 5,
      FridgeFactor: 5,
      LootRespawn: 2,
      TimeSinceApo: 1,
      PlantResilience: 3,
      PlantAbundance: 3,
      EndRegen: 5,
      ZombieLore: {
        Speed: 3,
        Strength: 3,
        Toughness: 3,
        Transmission: 1,
        Mortality: 6,
        Reanimate: 1,
        Cognition: 3,
        Memory: 2,
        Decomp: 1,
        Sight: 3,
        Hearing: 3,
        Smell: 3,
        ThumpNoChasing: true,
        ThumpOnConstruction: true,
        ActiveOnly: 1,
        TriggerHouseAlarm: false,
        ZombiesDragDown: false,
        ZombiesFenceLunge: true,
      },
      ZombieConfig: {
        PopulationMultiplier: 0.2,
        PopulationStartMultiplier: 1.0,
        PopulationPeakMultiplier: 1.5,
        PopulationPeakDay: 28,
        RespawnHours: 72.0,
        RespawnUnseenHours: 16.0,
        RespawnMultiplier: 0.1,
        RedistributeHours: 12.0,
        FollowSoundDistance: 100,
        RallyGroupSize: 20,
        RallyTravelDistance: 20,
        RallyGroupSeparation: 15,
        RallyGroupRadius: 3,
      },
    },
  },
};

export function getPreset(id: string): SandboxVars | undefined {
  return DIFFICULTY_PRESETS[id]?.config;
}

export function getPresetLabel(id: string): string {
  return DIFFICULTY_PRESETS[id]?.label ?? 'Custom';
}

export const PRESET_IDS = Object.keys(DIFFICULTY_PRESETS) as string[];
