export interface ZombieLore {
  Speed?: number;
  SprinterPercentage?: number;
  Strength?: number;
  Toughness?: number;
  Transmission?: number;
  Mortality?: number;
  Reanimate?: number;
  Cognition?: number;
  CrawlUnderVehicle?: number;
  Memory?: number;
  Sight?: number;
  Hearing?: number;
  Smell?: number;
  SpottedLogic?: boolean;
  ThumpNoChasing?: boolean;
  ThumpOnConstruction?: boolean;
  ActiveOnly?: number;
  TriggerHouseAlarm?: boolean;
  ZombiesDragDown?: boolean;
  ZombiesCrawlersDragDown?: boolean;
  ZombiesFenceLunge?: boolean;
  ZombiesArmorFactor?: number;
  ZombiesMaxDefense?: number;
  ChanceOfAttachedWeapon?: number;
  ZombiesFallDamage?: number;
  DisableFakeDead?: number;
  PlayerSpawnZombieRemoval?: number;
  FenceThumpersRequired?: number;
  FenceDamageMultiplier?: number;
}

export interface ZombieConfig {
  PopulationMultiplier?: number;
  PopulationStartMultiplier?: number;
  PopulationPeakMultiplier?: number;
  PopulationPeakDay?: number;
  RespawnHours?: number;
  RespawnUnseenHours?: number;
  RespawnMultiplier?: number;
  RedistributeHours?: number;
  FollowSoundDistance?: number;
  RallyGroupSize?: number;
  RallyGroupSizeVariance?: number;
  RallyTravelDistance?: number;
  RallyGroupSeparation?: number;
  RallyGroupRadius?: number;
  ZombiesCountBeforeDelete?: number;
}

export interface MultiplierConfig {
  Global?: number;
  GlobalToggle?: boolean;
  Fitness?: number;
  Strength?: number;
  Sprinting?: number;
  Lightfoot?: number;
  Nimble?: number;
  Sneak?: number;
  Axe?: number;
  Blunt?: number;
  SmallBlunt?: number;
  LongBlade?: number;
  SmallBlade?: number;
  Spear?: number;
  Maintenance?: number;
  Woodwork?: number;
  Cooking?: number;
  Farming?: number;
  Doctor?: number;
  Electricity?: number;
  MetalWelding?: number;
  Mechanics?: number;
  Tailoring?: number;
  Aiming?: number;
  Reloading?: number;
  Fishing?: number;
  Trapping?: number;
  PlantScavenging?: number;
  FlintKnapping?: number;
  Masonry?: number;
  Pottery?: number;
  Carving?: number;
  Husbandry?: number;
  Tracking?: number;
  Blacksmith?: number;
  Butchering?: number;
  Glassmaking?: number;
}

export interface SandboxVars {
  VERSION?: number;
  Zombies?: number;
  Distribution?: number;
  DayLength?: number;
  StartYear?: number;
  StartMonth?: number;
  StartDay?: number;
  StartTime?: number;
  DayNightCycle?: number;
  ClimateCycle?: number;
  FogCycle?: number;
  WaterShut?: number;
  ElecShut?: number;
  AlarmDecay?: number;
  WaterShutModifier?: number;
  ElecShutModifier?: number;
  AlarmDecayModifier?: number;
  FoodLootNew?: number;
  LiteratureLootNew?: number;
  MedicalLootNew?: number;
  SurvivalGearsLootNew?: number;
  CannedFoodLootNew?: number;
  WeaponLootNew?: number;
  RangedWeaponLootNew?: number;
  AmmoLootNew?: number;
  MechanicsLootNew?: number;
  OtherLootNew?: number;
  ClothingLootNew?: number;
  ContainerLootNew?: number;
  KeyLootNew?: number;
  MediaLootNew?: number;
  MementoLootNew?: number;
  CookwareLootNew?: number;
  MaterialLootNew?: number;
  FarmingLootNew?: number;
  ToolLootNew?: number;
  RollsMultiplier?: number;
  LootItemRemovalList?: string;
  RemoveStoryLoot?: boolean;
  RemoveZombieLoot?: boolean;
  ZombiePopLootEffect?: number;
  InsaneLootFactor?: number;
  ExtremeLootFactor?: number;
  RareLootFactor?: number;
  NormalLootFactor?: number;
  CommonLootFactor?: number;
  AbundantLootFactor?: number;
  Temperature?: number;
  Rain?: number;
  ErosionSpeed?: number;
  ErosionDays?: number;
  Farming?: number;
  CompostTime?: number;
  StatsDecrease?: number;
  NatureAbundance?: number;
  Alarm?: number;
  LockedHouses?: number;
  StarterKit?: boolean;
  Nutrition?: boolean;
  FoodRotSpeed?: number;
  FridgeFactor?: number;
  SeenHoursPreventLootRespawn?: number;
  HoursForLootRespawn?: number;
  MaxItemsForLootRespawn?: number;
  ConstructionPreventsLootRespawn?: boolean;
  WorldItemRemovalList?: string;
  HoursForWorldItemRemoval?: number;
  ItemRemovalListBlacklistToggle?: boolean;
  TimeSinceApo?: number;
  PlantResilience?: number;
  PlantAbundance?: number;
  EndRegen?: number;
  Helicopter?: number;
  MetaEvent?: number;
  SleepingEvent?: number;
  GeneratorFuelConsumption?: number;
  GeneratorSpawning?: number;
  AnnotatedMapChance?: number;
  CharacterFreePoints?: number;
  ConstructionBonusPoints?: number;
  NightDarkness?: number;
  NightLength?: number;
  BoneFracture?: boolean;
  InjurySeverity?: number;
  HoursForCorpseRemoval?: number;
  DecayingCorpseHealthImpact?: number;
  ZombieHealthImpact?: boolean;
  BloodLevel?: number;
  ClothingDegradation?: number;
  FireSpread?: boolean;
  DaysForRottenFoodRemoval?: number;
  AllowExteriorGenerator?: boolean;
  MaxFogIntensity?: number;
  MaxRainFxIntensity?: number;
  EnableSnowOnGround?: boolean;
  AttackBlockMovements?: boolean;
  SurvivorHouseChance?: number;
  VehicleStoryChance?: number;
  ZoneStoryChance?: number;
  AllClothesUnlocked?: boolean;
  EnableTaintedWaterText?: boolean;
  EnableVehicles?: boolean;
  CarSpawnRate?: number;
  ZombieAttractionMultiplier?: number;
  VehicleEasyUse?: boolean;
  InitialGas?: number;
  FuelStationGasInfinite?: boolean;
  FuelStationGasMin?: number;
  FuelStationGasMax?: number;
  FuelStationGasEmptyChance?: number;
  LockedCar?: number;
  CarGasConsumption?: number;
  CarGeneralCondition?: number;
  CarDamageOnImpact?: number;
  DamageToPlayerFromHitByACar?: number;
  TrafficJam?: boolean;
  CarAlarm?: number;
  PlayerDamageFromCrash?: boolean;
  SirenShutoffHours?: number;
  ChanceHasGas?: number;
  RecentlySurvivorVehicles?: number;
  MultiHitZombies?: boolean;
  RearVulnerability?: number;
  SirenEffectsZombies?: boolean;
  AnimalStatsModifier?: number;
  AnimalMetaStatsModifier?: number;
  AnimalPregnancyTime?: number;
  AnimalAgeModifier?: number;
  AnimalMilkIncModifier?: number;
  AnimalWoolIncModifier?: number;
  AnimalRanchChance?: number;
  AnimalGrassRegrowTime?: number;
  AnimalMetaPredator?: boolean;
  AnimalMatingSeason?: boolean;
  AnimalEggHatch?: number;
  AnimalSoundAttractZombies?: boolean;
  AnimalTrackChance?: number;
  AnimalPathChance?: number;
  MaximumRatIndex?: number;
  DaysUntilMaximumRatIndex?: number;
  MetaKnowledge?: number;
  SeeNotLearntRecipe?: boolean;
  MaximumLootedBuildingRooms?: number;
  EnablePoisoning?: number;
  MaggotSpawn?: number;
  LightBulbLifespan?: number;
  FishAbundance?: number;
  LevelForMediaXPCutoff?: number;
  LevelForDismantleXPCutoff?: number;
  BloodSplatLifespanDays?: number;
  LiteratureCooldown?: number;
  NegativeTraitsPenalty?: number;
  MinutesPerPage?: number;
  KillInsideCrops?: boolean;
  PlantGrowingSeasons?: boolean;
  PlaceDirtAboveground?: boolean;
  FarmingSpeedNew?: number;
  FarmingAmountNew?: number;
  MaximumLooted?: number;
  DaysUntilMaximumLooted?: number;
  RuralLooted?: number;
  MaximumDiminishedLoot?: number;
  DaysUntilMaximumDiminishedLoot?: number;
  MuscleStrainFactor?: number;
  DiscomfortFactor?: number;
  WoundInfectionFactor?: number;
  NoBlackClothes?: boolean;
  EasyClimbing?: boolean;
  MaximumFireFuelHours?: number;
  FirearmUseDamageChance?: boolean;
  FirearmNoiseMultiplier?: number;
  FirearmJamMultiplier?: number;
  FirearmMoodleMultiplier?: number;
  FirearmWeatherMultiplier?: number;
  FirearmHeadGearEffect?: boolean;
  ClayLakeChance?: number;
  ClayRiverChance?: number;
  GeneratorTileRange?: number;
  GeneratorVerticalPowerRange?: number;
  ZombieVoronoiNoise?: boolean;
  ZombieRespawn?: number;
  ZombieMigrate?: boolean;
  ZombieLore?: ZombieLore;
  ZombieConfig?: ZombieConfig;
  MultiplierConfig?: MultiplierConfig;
  Map?: { AllowMiniMap?: boolean; AllowWorldMap?: boolean; MapAllKnown?: boolean; MapNeedsLight?: boolean };
  Basement?: { SpawnFrequency?: number };
}

export type DifficultyPresetId = 'apocalypse' | 'survivor' | 'builder' | 'custom';

export interface DifficultyPreset {
  id: DifficultyPresetId;
  label: string;
  description: string;
  config: SandboxVars;
}

export interface SandboxOptionMeta {
  key: string;
  category: OptionCategory;
  label: string;
  description: string;
  type: 'number' | 'boolean' | 'select';
  min?: number;
  max?: number;
  options?: { value: number; label: string }[];
  nested?: boolean;
  nestedKey?: string;
}

export type OptionCategory =
  | 'population'
  | 'time'
  | 'world'
  | 'nature'
  | 'character'
  | 'zombie_lore'
  | 'zombie_config'
  | 'multiplier_config'
  | 'meta'
  | 'loot'
  | 'vehicle';

export interface SandboxVarsUpdateRequest {
  config?: SandboxVars;
  updates?: Partial<SandboxVars>;
  applyPreset?: DifficultyPresetId;
}

export interface SandboxVarsResponse {
  serverName: string;
  config: SandboxVars;
  filePath: string;
  exists: boolean;
}

export function createDefaultSandboxVars(): SandboxVars {
  return {
    VERSION: 4,
    Zombies: 4,
    Distribution: 1,
    DayLength: 3,
    StartYear: 1,
    StartMonth: 7,
    StartDay: 9,
    StartTime: 2,
    WaterShut: 2,
    ElecShut: 2,
    WaterShutModifier: 500,
    ElecShutModifier: 480,
    Temperature: 3,
    Rain: 3,
    ErosionSpeed: 5,
    Farming: 3,
    StatsDecrease: 4,
    NatureAbundance: 3,
    Alarm: 6,
    LockedHouses: 6,
    StarterKit: false,
    Nutrition: true,
    FoodRotSpeed: 5,
    FridgeFactor: 5,
    TimeSinceApo: 1,
    PlantResilience: 3,
    PlantAbundance: 3,
    EndRegen: 3,
    ZombieLore: {
      Speed: 3,
      Strength: 2,
      Toughness: 2,
      Transmission: 1,
      Mortality: 6,
      Reanimate: 1,
      Cognition: 3,
      Memory: 2,
      Sight: 2,
      Hearing: 2,
      SpottedLogic: true,
      ThumpNoChasing: true,
      ThumpOnConstruction: true,
      ActiveOnly: 1,
      TriggerHouseAlarm: false,
      ZombiesDragDown: true,
      ZombiesFenceLunge: true,
    },
    ZombieConfig: {
      PopulationMultiplier: 1.0,
      PopulationStartMultiplier: 1.0,
      PopulationPeakMultiplier: 1.5,
      PopulationPeakDay: 28,
      RespawnHours: 72.0,
      RespawnUnseenHours: 16.0,
      RespawnMultiplier: 0.1,
      RedistributeHours: 12.0,
      FollowSoundDistance: 100,
      RallyGroupSize: 20,
      RallyTravelDistance: 20,
      RallyGroupSeparation: 15,
      RallyGroupRadius: 3,
    },
  };
}
